### ISSUE TITLE
regex does not find empty string link

### ISSUE THREAD

**Issue by RamanjitKhakh** [gakimball/transform-markdown-links#1]
Hello, 

I was using your module and I think it works really well. The only issue I found was if I try to parse:

```
![](/resources/some_image.JPG)
```

that link will not be picked up in the capture group. I am writing a script that parses markdown and in some cases, the links are formated like that. I tested your regex and I was able to get it working for my case

```
\[([^\]]+)*\]\(([^\)]+)\)
```

I thought it would help if you include this regex to capture zero or characters in the first capture group.

Lemme know your thoughts

Thanks

**Comment by RamanjitKhakh** [comment]
I have also created a PR for this issue here 

https://github.com/gakimball/transform-markdown-links/pull/2

**Comment by gakimball** [comment]
Merged #2

**Comment by gakimball** [comment]
Published 1.0.1 with this fix.
