### ISSUE TITLE
Misses links that are defined elsewhere.

### ISSUE THREAD

**Issue by fidian** [gakimball/transform-markdown-links#3]
I have markdown that uses the following syntax:

    Check out the [example] for further information.

    See also: our [excellent example][example].

    [example]: http://example.com

The above links should both reference the link definition at the bottom of the document, though the link definition could appear anywhere. The format for those links is as follows, from [daringfireball](http://daringfireball.net/projects/markdown/syntax):

> Then, anywhere in the document, you define your link label like this, on a line by itself:
>
> `[id]: http://example.com/  "Optional Title Here"`
>
>That is:
>
> * Square brackets containing the link identifier (optionally indented from the left margin using up to three spaces);
> * followed by a colon;
> * followed by one or more spaces (or tabs);
> * followed by the URL for the link;
> * optionally followed by a title attribute for the link, enclosed in double or single quotes, or enclosed in parentheses.
>
> The following three link definitions are equivalent:
>
> `[foo]: http://example.com/  "Optional Title Here"`
> `[foo]: http://example.com/  'Optional Title Here'`
> `[foo]: http://example.com/  (Optional Title Here)`
>
> NOTE: There is a known bug in Markdown.pl 1.0.1 which prevents single quotes from being used to delimit link titles.
>
> The link URL may, optionally, be surrounded by angle brackets:
>
> `[id]: <http://example.com/>  "Optional Title Here"`
>
> You can put the title attribute on the next line and use extra spaces or tabs for padding, which tends to look better with longer URLs:
>
> ```
> [id]: http://example.com/longish/path/to/resource/here
>    "Optional Title Here"
> ```

**Comment by gakimball** [comment]
Fix later this week!

**Comment by gakimball** [comment]
Addressed in 1.1.0 (and 2.0.0, which is the same thing but requires Node 4). Let me know if it works for you.

**Comment by fidian** [comment]
Thanks, seems to do the trick. :-)
